# Generated by Django 3.2 on 2023-02-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentnews',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='recentnews',
            name='author',
        ),
        migrations.AddField(
            model_name='recentnews',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
