# Generated by Django 3.2 on 2023-02-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20230222_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentnews',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
