# Generated by Django 3.2 on 2023-03-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230302_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abv',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ml',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
